syntax = "proto3";

package orderflow.payment.commands.v1;

option java_package = "com.echcherqaoui.orderflow.contracts.payment.commands.v1";
option java_multiple_files = true;

import "orderflow/common/v1/metadata.proto";

message ChargePaymentCommand {
  orderflow.common.v1.MessageMetadata metadata = 1;
  string order_id = 2;
  string user_id = 3;
  int64 total_price_cents = 4;
  string currency = 5;
}

message CancelPaymentCommand {
  orderflow.common.v1.MessageMetadata metadata = 1;
  string order_id = 2;
  string payment_intent_id = 3;
  string reason = 4;
}