services:
  terraform:
    image: hashicorp/terraform:${TERRAFORM_VERSION}
    container_name: tf-kafka-manager
    environment:
      TF_VAR_kafka_broker: kafka-0:${KF_INTERNAL_PORT}
    volumes:
      - ../terraform:/workspace
    working_dir: /workspace
    networks:
      - orderflow-net
    entrypoint: [ "terraform" ]
    command: ["init"]

networks:
  orderflow-net:
    external: true